---
########################################################
# Set up Logstash
########################################################

- name: Download Logstash Deb Package
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-7.9.0.deb"
    dest: "/tmp"

- name: Install Logstash Deb Package
  become: yes
  apt:
    deb: "/tmp/logstash-7.9.0.deb"

- name: Create Logstash Pipeline File
  become: yes
  file:
      path: /etc/logstash/conf.d/main.conf
      state: touch

- name: Add Logstash Pipeline Configuration
  become: yes
  blockinfile:
      path: /etc/logstash/conf.d/main.conf
      marker: ""
      block: |
          input {
           beats {
             port => 5044
             host => "localhost"
           }
          }

          filter {
           grok {
            match => {"message" => "%{COMBINEDAPACHELOG}"}
           }
          }

          output {
           elasticsearch { hosts => ["localhost:9200"] }
           stdout { codec => rubydebug }
          }
          
- name: Start Logstash Service
  become: yes
  service:
    name: logstash
    state: started
