---
#
# Playbook to install the ELK stack + Beats
#
- hosts: localhost
  connection: local
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
  - { role: logstash }
  - { role: elasticsearch }
  - { role: kibana }
  - { role: filebeat }
